### ISSUE TITLE
Create basic structure for Address entity

### ISSUE THREAD

**Issue by AtulDwivedi** [AtulDwivedi/CakeShop#4]
Do similar to https://github.com/AtulDwivedi/CakeShop/issues/3

**Comment by AtulDwivedi** [comment]
I think you have just added sql file. 

This is not done, you need to create dummy Servlet, Service, Dao - interfaces and classes.

You need to click on #3 link in the issue description, it will tell what needs to be done for address. 

Initial structure means everything from servlet to dao layer.

**Comment by Charu24** [comment]
ok sir 
There was confusion as per task title. 
I will do it correct
Thanks
