### ISSUE TITLE
Externalize database properties

### ISSUE THREAD

**Issue by AtulDwivedi** [AtulDwivedi/CakeShop#7]
Currently in DbUtil.java database **url**, **username** and **password** is hard coded. This is not a good practice. all the propeties should be taken from external file, in such a way it is easy to maintain and change.

## What you need to do?
- Create db.properties file in dao package
- Put **url**, **username** and **password** in the file
- User resource boundle to read the values from properties file in DbUtil.java
- Create `Connection` type of object and then return
- Take help from class notes: [here](https://github.com/WeInnovate/JM2006/tree/master/src/com/jm2006/learn/jdbc/util)

**Comment by sangues** [comment]
Sir, what's left in my task.....?????
